ptz_relative:
  name: PTZ (RelativeMove)
  description: >
    If your ONVIF camera supports RelativeMove PTZ, you will be able to pan,
    tilt or zoom your camera. Not all cameras which support PTZ support
    RelativeMove. Camera devices may have multiple PTZ nodes, you usually want
    to select a single entity rather than a device.
  target:
    entity:
      integration: onvif_ptz
      domain: button
    device:
      integration: onvif_ptz
  fields:
    translation:
      name: Translation
      description: "How to translate the camera (usually, {PanTilt: {x: 0, y: 0}, Zoom: 0})"
      selector:
        object:
    speed:
      name: Speed
      description: How fast to translate the camera (optional, same format as translation)
      selector:
        object:

ptz_absolute:
  name: PTZ (AbsoluteMove)
  description: >
    If your ONVIF camera supports AbsoluteMove PTZ, you will be able to pan,
    tilt or zoom your camera. Not all cameras which support PTZ support
    absoluteMove. Camera devices may have multiple PTZ nodes, you usually want
    to select a single entity rather than a device.
  target:
    entity:
      integration: onvif_ptz
      domain: button
    device:
      integration: onvif_ptz
  fields:
    position:
      name: Position
      description: "Where to move the camera to (usually, {PanTilt: {x: 0, y: 0}, Zoom: 0})"
      selector:
        object:
    speed:
      name: Speed
      description: "How fast to translate the camera (optional, {PanTilt: {x: 0, y: 0}, Zoom: 0})"
      selector:
        object:

ptz_continuous:
  name: PTZ (ContinuousMove)
  description: >
    If your ONVIF camera supports ContinuousMove PTZ, you will be able to pan,
    tilt or zoom your camera. Not all cameras which support PTZ support
    absoluteMove. Camera devices may have multiple PTZ nodes, you usually want
    to select a single entity rather than a device.
  target:
    entity:
      integration: onvif_ptz
      domain: button
    device:
      integration: onvif_ptz
  fields:
    velocity:
      name: Velocity
      description: "How to translate the camera (usually, {PanTilt: {x: 0, y: 0}, Zoom: 0})"
      selector:
        object:
    speed:
      name: Speed
      description: How fast to translate the camera (optional, same format as translation)
      selector:
        object:

ptz_stop:
  name: PTZ (Stop)
  description: >
    If your ONVIF camera supports PTZ, you will be able to pan, tilt or zoom
    your camera. This command stops any ongoing movement. Not all cameras which
    support PTZ support absoluteMove. Camera devices may have multiple PTZ
    nodes, you usually want to select a single entity rather than a device.
  target:
    entity:
      integration: onvif_ptz
      domain: button
    device:
      integration: onvif_ptz
  fields:
    pan_tilt:
      name: Stop Pan/Tilt
      description: Stop pan/tilt
      selector:
        boolean:
    speed:
      name: Stop Zoom
      description: Stop zoom
      selector:
        boolean: